services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14250:14250"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./alloy.river:/etc/alloy/config.river:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
    command: ["run", "/etc/alloy/config.river"]
    depends_on:
      - loki