receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  resource:
    attributes:
      - key: service.name
        from_attribute: service.name
        action: upsert

exporters:
  debug:
    verbosity: detailed

  file:
    path: /var/log/otel-collector/logs.json

  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [file, debug]

