server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: otel-collector-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: "otel-collector"
          __path__: /var/log/otel-collector/logs.json

    pipeline_stages:
      - cri: {}
      - json:
          expressions:
            ## Log Structure
            service: resource.attributes['service.name']
            trace_id: body.trace_id || trace_id
            severity: severity_text || severity
            message: body.body || body || body.message || message
      - labels:
          service:
          severity:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

